version: "3.8"
services:
    server-staging:
        build:
            context: ../../
            dockerfile: ./docker/staging/Dockerfile
        ports:
            - "8083:8083"
        env_file:
            - ../../staging.env
        environment:
            - NODE_ENV=development
        depends_on:
            - mongodb-staging
        volumes:
            - ../../src:/server/src
            - /server/node_modules
        networks:
            - staging_network

    mongodb-staging:
        image: mongo:latest
        ports:
            - "27018:27017"
        volumes:
            - mongodb_staging_data:/data/db
        networks:
            - staging_network

    networks:
        staging_network:
            driver: bridge

    volumes:
        mongodb_staging_data:
