version: "3.8"
services:
    server:
        build:
            context: ../../
            dockerfile: ./docker/staging/Dockerfile
        ports:
            - "8083:8083"
        env_file:
            - ../../staging.env
        environment:
            - NODE_ENV=production
